### PR TITLE
Move regenerate docs to subcrate as well

### PR DESCRIPTION
**Pull request by ice1000**
Signed-off-by: ice1000 <ice1000kotlin@foxmail.com>

As title, because the regeneration should now be done by running the command in the subcrate (instead of the raft crate).
Added docs.rs and crates.io badges for the subcrate by the way.

### CODE REVIEW

**Comment by ice1000** [comment]
PTAL @Hoverbear

**Comment by ice1000** [comment]
PTAL @Hoverbear

**Comment by ice1000** [comment]
merge? @Hoverbear

**Comment by Hoverbear** [comment]
Was waiting on CI, sorry :(

**Comment by ice1000** [comment]
No worries

**Pull request merged**
