### PR TITLE
docs: remove ignore codefences for examples

### LINKED ISSUE #70: Tested examples in src/lib.rs Rustdocs
https://github.com/pingcap/raft-rs/pull/69 introduces examples for usage to src/lib.rs. However most of them  are not actually compiled or tested.

We would like them to remove the `ignore` from the code fences so the examples are tested.

Please use [hiding](https://doc.rust-lang.org/1.24.1/rustdoc/documentation-tests.html#hiding-portions-of-the-example) in the examples to keep the redundant setup code from getting in the way.

@hoverbear is very happy to help mentor this issue. Just ping. :)

### PR DESCRIPTION
**Pull request by psinghal20**
Remove code fences to compile and test examples. 

Fixes #70, Redo #194

### CODE REVIEW

**Comment by BusyJay** [comment]
Cool, looks good to me generally. Can you update the PR to adapt the latest APIs from master?

**Comment by psinghal20** [comment]
@BusyJay Done. PTAL

**Comment by siddontang** [comment]
PTAL @Hoverbear @nrc

**Comment by Hoverbear** [comment]
Thanks for this contribution, @psinghal20 :)

**Pull request merged**
