### PR TITLE
Fix Rust RFC 344

### PR DESCRIPTION
**Pull request by PumpkinSeed**
Fixing #223 except the `src/prost/wrapper_eraftpb.rs`

### CODE REVIEW

**Comment by Hoverbear** [comment]
@PumpkinSeed According to https://travis-ci.org/pingcap/raft-rs/jobs/529274551 can you please run Rustfmt? (You can ignore the broken windows nightly build. It is passing but not realizing it is passing.)

**Comment by PumpkinSeed** [comment]
Done

**Comment by PumpkinSeed** [comment]
I resolved the merge conflicts, it causes some build issue. I will solve them when I will have time.

**Comment by Hoverbear** [comment]
@PumpkinSeed I think it's just a `cargo fmt` :)

**Comment by PumpkinSeed** [comment]
I checked out and most of the functions what it's solving are already done, so it make sense to close this PR.

**Comment by Hoverbear** [comment]
@PumpkinSeed Thanks so much for doing this work anyways. :)

**Pull request closed without merging**
