### PR TITLE
Format the src/prost.rs to stay consistent with the current one

### PR DESCRIPTION
**Pull request by Fullstop000**
Signed-off-by: Fullstop000 <fullstop1005@gmail.com>

### CODE REVIEW

**Comment by siddontang** [comment]
so maybe it is better to run `cargo fmt` in the end of `build.rs`? 
@nrc

**Comment by BusyJay** [comment]
I think it's a bad idea to format generated files. Basic readability is enough.

**Comment by nrc** [comment]
> so maybe it is better to run cargo fmt in the end of build.rs?

there is a convenience function in protobuf-build called `rustfmt` to make this really easy?

> I think it's a bad idea to format generated files

Why?

Note that this file is not just generated into `target`, it is generated into `src` and committed to the repo so we should expect people to read it.

**Comment by BusyJay** [comment]
In my opinion, automatically generated files are not expected to be read by people exact the compiler authors. People generally should read the proto files instead. Expect people reading those means we may need to do more to make it readable such as comments and API docs.

**Comment by nrc** [comment]
I would agree if the file were only generated and then discarded, but in this case the file is committed to the repo, so we should expect that people might read it. It can actually be useful to read the generated source code as well as the proto file to find the signatures of the generated functions (which are not obvious from the proto file).

Part of the reason for migrating to Prost is so that we preserve the comments into the generated code. I don't think there is much that would be interesting to add as API docs, but `cargo doc` will generate docs which at least tell you what is there.

**Comment by Fullstop000** [comment]
@nrc How about removing `src/prost.rs` and just using `src/prost/mod.rs` since we dynamically generate some files in `build.rs`?

**Comment by nrc** [comment]
> How about removing src/prost.rs and just using src/prost/mod.rs

I don't think it makes any difference? Why would this change things?

**Comment by Fullstop000** [comment]
Using `include!` in `src/prost.rs` to include things in `src/prost/*` is a little weird for me. But it's ok to keep it.

**Comment by nrc** [comment]
> Using include! in src/prost.rs to include things in src/prost/* is a little weird for me. But it's ok to keep it.

We would still need to use `include!` in `src/prost/mod.rs`, but I don't mind which one to use

**Comment by ice1000** [comment]
I suppose this is a part of #218 (see https://github.com/pingcap/raft-rs/pull/218/files#diff-a7b0a2dee0126cddf994326e705a91eaR89)

**Comment by ice1000** [comment]
Instead of generating more beautiful code, I recommend generating as less code as possible and delegate everything rustfmt

**Comment by Hoverbear** [comment]
Really appreciate this PR @Fullstop000 , we just merged #218, do you think we should keep this?

**Comment by Fullstop000** [comment]
@Hoverbear it's ok for me to close this since we run `rustfmt` at the end of `build.rs` 🎉

**Pull request closed without merging**
