### PR TITLE
Fixes #211, replace all `new_` with `default`

### LINKED ISSUE #211: Resolve issue with `new_` from protobuf bindings
We currently use `new_` to replace the `new` from rust-protobuf in our protobuf bindings. We should change that to something less ugly, probably using the `Default` trait.

### PR DESCRIPTION
**Pull request by ice1000**
This PR can close #211.

Signed-off-by: ice1000 <ice1000kotlin@foxmail.com>

### CODE REVIEW

**Comment by ice1000** [comment]
```
error: unused return value of `std::result::Result::<T, E>::is_ok` that must be used
   --> src/raft.rs:785:9
    |
785 |         self.step(m).is_ok();
    |         ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `-D unused-must-use` implied by `-D warnings`
error: unused return value of `std::result::Result::<T, E>::is_ok` that must be used
   --> src/raft.rs:801:17
    |
801 |                 self.step(m).is_ok();
    |                 ^^^^^^^^^^^^^^^^^^^^^
error: unused return value of `std::result::Result::<T, E>::is_ok` that must be used
   --> src/raft.rs:816:13
    |
816 |             self.step(m).is_ok();
    |             ^^^^^^^^^^^^^^^^^^^^^
error: unused return value of `std::result::Result::<T, E>::is_ok` that must be used
   --> src/raw_node.rs:446:9
    |
446 |         self.raft.step(m).is_ok();
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^
error: unused return value of `std::result::Result::<T, E>::is_ok` that must be used
   --> src/raw_node.rs:457:9
    |
457 |         self.raft.step(m).is_ok();
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^
error: unused return value of `std::result::Result::<T, E>::is_ok` that must be used
   --> src/raw_node.rs:465:9
    |
465 |         self.raft.step(m).is_ok();
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^
error: unused return value of `std::result::Result::<T, E>::is_ok` that must be used
   --> src/raw_node.rs:478:9
    |
478 |         self.raft.step(m).is_ok();
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^
error: aborting due to 7 previous errors
```

These errors come from master code. Am I supposed to fix them?

**Comment by hicqu** [comment]
@ice1000 I think you can just fix them. BTW I think we also need to port this into raft 0.4, what do you think?

**Comment by ice1000** [comment]
@hicqu I can do the porting as well.

**Comment by hicqu** [comment]
LGTM.

**Pull request merged**
