### PR TITLE
[WIP] Introduce Failure.

### PR DESCRIPTION
**Pull request by Hoverbear**
**WIP:** Please note I haven't fully groomed this PR and I'd like to place some effort in writing a proper ticket for it. Feel free to provide feedback at this point though.

---

Prior to this change, we used quick_error.

This change introduces Failure in the Error & ErrorKind strategy.

For more information on this style: https://boats.gitlab.io/failure/error-errorkind.html

### CODE REVIEW

**Comment by stephanbuys** [comment]
@Hoverbear awesome, have you had success using this repo for some 'rafting' yet?

**Comment by siddontang** [comment]
Hi @stephanbuys 

This repo is the same as current TiKV's, so I think we can use it directly in production. But now we miss examples and documents to let the user use it easily.

@Hoverbear will help us first improve the error handling with introducing failure, then use this raft library in TiKV.

**Comment by stephanbuys** [comment]
This is great, I will keep my eye on the repo and start trying it out as soon as the first basic examples start working

**Comment by Hoverbear** [comment]
@stephanbuys This is one of my goals for the next few months. :) I'd like to get this `raft-rs` in a state where I can start pointing people looking at https://github.com/Hoverbear/raft-rs/ here. =D

**Comment by Hoverbear** [comment]
I'm going to close this but we still intend to move to failure at some point in the future. There is a new version and this PR is quite stale.

**Pull request closed without merging**
