### PR TITLE
tests: add case test_add_node_check_quorum

### PR DESCRIPTION
**Pull request by july2993**
contribute to https://github.com/pingcap/raft-rs/issues/23
add test test_add_node_check_quorum

i use rustfmt 0.3.6(specified in the travis.yml) to format all the code, it seems the current code mostly was formatted by 0.2.* like the previous code in tikv,  and some code use other rustfmt version in the recent pr, maybe we must make sure which version to use and check it in CI.

### CODE REVIEW

**Comment by BusyJay** [comment]
Thank you! But please don't do the format yet, it's hard to review and distracting. We will format all the code later.

**Comment by july2993** [comment]
no format now

**Comment by siddontang** [comment]
LGTM

**Comment by BusyJay** [comment]
@july2993 Thanks for your contribution! 🍺

**Pull request merged**
