### PR TITLE
Bump three dependencies

### PR DESCRIPTION
**Pull request by ice1000**
Signed-off-by: ice1000 <ice1000kotlin@foxmail.com>

As title.

### CODE REVIEW

**Comment by ice1000** [comment]
```
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.6/src/error_impls.rs:13:5
   |
8  | extern crate std;
   | ----------------- not an extern crate passed with `--extern`
...
13 | use std::{error, io};
   |     ^^^
   |
note: this import refers to the extern crate imported here
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.6/src/error_impls.rs:8:1
   |
8  | extern crate std;
   | ^^^^^^^^^^^^^^^^^
                                                                                
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.6/src/use_file.rs:15:5
   |
10 | extern crate std;
   | ----------------- not an extern crate passed with `--extern`
...
15 | use std::{fs::File, io::Read};
   |     ^^^
   |
note: this import refers to the extern crate imported here
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.6/src/use_file.rs:10:1
   |
10 | extern crate std;
   | ^^^^^^^^^^^^^^^^^
                                                                                
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.6/src/linux_android.rs:15:5
   |
10 | extern crate std;
   | ----------------- not an extern crate passed with `--extern`
...
15 | use std::io;
   |     ^^^
   |
note: this import refers to the extern crate imported here
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.6/src/linux_android.rs:10:1
   |
10 | extern crate std;
   | ^^^^^^^^^^^^^^^^^
                                                                                
error: aborting due to 3 previous errors
```

Why? Does this mean we have to drop rust 1.31 support?

**Comment by nrc** [comment]
The crate getrandom only supports Rust 1.32 and later (see https://github.com/rust-random/getrandom and brief discussion at https://github.com/rust-random/getrandom/pull/15#pullrequestreview-217912149), so if we want to keep that dep, then I think we to drop 1.31 support (which isn't such a bad thing, IMO we should only support current stable).

**Comment by ice1000** [comment]
> The crate getrandom only supports Rust 1.32 and later (see https://github.com/rust-random/getrandom and brief discussion at [rust-random/getrandom#15 (review)](https://github.com/rust-random/getrandom/pull/15#pullrequestreview-217912149)), so if we want to keep that dep, then I think we to drop 1.31 support (which isn't such a bad thing, IMO we should only support current stable).

Ok (and it sounds like it's not an issue of my own dependency bump)

**Comment by ice1000** [comment]
PTAL @Hoverbear

**Pull request merged**
