### PR TITLE
Correct learner checking in handle_transfer_leader

### PR DESCRIPTION
**Pull request by Fullstop000**
#164

### CODE REVIEW

**Comment by Fullstop000** [comment]
Got CI error from AppVeyor
```
git clone -q https://github.com/pingcap/raft-rs.git C:\projects\raft-rs
fatal: unable to access 'https://github.com/pingcap/raft-rs.git/': Could not resolve host: github.com
```
Is there something wrong with the server 🤔️ ? @Hoverbear

**Comment by Hoverbear** [comment]
@Fullstop000 Sometimes Appveyor is lazy. 😆

**Comment by hicqu** [comment]
LGTM.

**Comment by Hoverbear** [comment]
Thanks again for your contribution, @Fullstop000 ! :)

**Pull request merged**
