### PR TITLE
Correct the instructions of regenerating protobufs

### PR DESCRIPTION
**Pull request by Fullstop000**
Signed-off-by: Fullstop000 <fullstop1005@gmail.com>

### CODE REVIEW

**Comment by Fullstop000** [comment]
Maybe just remove the `Regenerate Protobufs` section ? 

And one more thing is that the actual `eraftpb.rs` file is a little hard to located. The `eraftpb.rs` will be created under `target/debug/build/raft-proto-***/out` but there are usually a lot of `raft-proto-***` so that I don't know which is the newest being generated.

**Comment by nrc** [comment]
> Maybe just remove the Regenerate Protobufs section ?

sgtm

> And one more thing is that the actual eraftpb.rs file is a little hard to locate

The easiest way is to run `cargo clean` before you build. There will then only be two raft-proto directories and only one will have an `out` sub-directory.

**Comment by Fullstop000** [comment]
Using `cargo clean` before re-building could be frustrating because it takes time re-compiling without caches :( .

I tried `cargo clean -p` but it only removes things in `deps`.

**Comment by Fullstop000** [comment]
> And one more thing is that the actual eraftpb.rs file is a little hard to locate

For anyone who has the same problem, I find that RLS is useful to deal with this.

**Pull request merged**
